
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp_declarative_wordpress
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - wp_network

  db:
    image: mariadb:10.5
    container_name: wp_declarative_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - wp_network

volumes:
  db_data:

networks:
  wp_network: